### ISSUE TITLE
使用wheelView布局，滚动界面最顶端或者最低端出现了一个空白的选项，onItemSelected回调值-1

### ISSUE THREAD

**Issue by mingzaizai** [Bigkoo/Android-PickerView#527]
使用wheelView布局，setAdapter后，滚动界面到最顶端或者最低端，再继续滚动会出现了一个空白的选项，onItemSelected回调值-1，数据在30条以上出现，几条数据没出现，请问下什么原因？
![device-2018-03-29-152219](https://user-images.githubusercontent.com/11647342/38075571-5ae72034-3365-11e8-8afb-fca0f278b617.png)
![whe](https://user-images.githubusercontent.com/11647342/38075582-64fe3fee-3365-11e8-8067-8b42c97e5b6b.png)

**Comment by mingzaizai** [comment]
使用已经封装好的OptionsPickerView 也会出现这个问题

**Comment by xiaosong520** [comment]
@mingzaizai 感谢反馈，下班后会排查一下原因。

**Comment by jkdevKK** [comment]
@xiaosong520 嗯，之前应该没有这个问题，更新之后出现的
做地址选择的时候出现了，去掉一两个地址又不会出现空白，原因不明

**Comment by jkdevKK** [comment]
@xiaosong520  V3.2.6版本没有这个问题，已查证

**Comment by xiaosong520** [comment]
@jkdevKK 能否告知发生问题的是哪个版本，以及代码的相关设置？  刚刚使用4.x版本没法复现该问题。初步猜测是，边缘滑动判断有误差，导致滑动越界从而选中边界外的item了。

**Comment by xiaosong520** [comment]
@mingzaizai @jkdevKK  v4.1.1 版本 对WheelView 临界项的滑动触摸事件做了预防处理，可以试试新版本。若有问题欢迎反馈~ 谢谢了

**Comment by mingzaizai** [comment]
1 使用compile 'com.contrarywind:wheelview:4.0.3'还是会存在这个问题（这个并没有更新成4.1.1），
2 使用compile 'com.contrarywind:Android-PickerView:4.1.1'，最终用的wheelview还是4.0.3版本的，问题没有得到解决。
![qq20180402-0](https://user-images.githubusercontent.com/11647342/38180330-5fab5b5c-365e-11e8-903d-ced87c65fd53.png)
![device-2018-04-02-095710](https://user-images.githubusercontent.com/11647342/38180506-b85b6dea-365f-11e8-8494-abe54aca2095.png)

**Comment by xiaosong520** [comment]
@mingzaizai 重现出来了。目前定位到是WheelView 类 646行内部的逻辑有问题导致。下班会抽时间优化此处的逻辑代码，  感谢反馈~

**Comment by xiaosong520** [comment]
@mingzaizai 已修复。 wheelview 版本v4.0.4    pickerview版本 v4.1.2 。

**Comment by mingzaizai** [comment]
测试正常，感谢！

**Comment by lichaohuilala** [comment]
我也遇到这个问题了，但是我不想更新版本，需要修改那些代码 ？

**Comment by mingzaizai** [comment]
那就下载他的新版，看他对这块做了哪些修改，移植过来------------------ 原始邮件 ------------------
发件人: "lichaohuilala"<notifications@github.com>
发送时间: 2019年5月28日(星期二) 下午2:31
收件人: "Bigkoo/Android-PickerView"<Android-PickerView@noreply.github.com>;
抄送: "mingzaizai"<384627918@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Bigkoo/Android-PickerView] 使用wheelView布局，滚动界面最顶端或者最低端出现了一个空白的选项，onItemSelected回调值-1 (#527)



我也遇到这个问题了，但是我不想更新版本，需要修改那些代码 ？
 
&mdash;

**Comment by lichaohuilala** [comment]
好的，感谢🙏。------------------ 原始邮件 ------------------
发件人: "mingzaizai"<notifications@github.com>
发送时间: 2019年5月28日(星期二) 下午5:58
收件人: "Bigkoo/Android-PickerView"<Android-PickerView@noreply.github.com>;
抄送: "lichaohuilala"<578078578@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Bigkoo/Android-PickerView] 使用wheelView布局，滚动界面最顶端或者最低端出现了一个空白的选项，onItemSelected回调值-1 (#527)


那就下载他的新版，看他对这块做了哪些修改，移植过来------------------ 原始邮&#x4EF6; ------------------ 
 发&#x4EF6;人: "lichaohuilala"<notifications@github.com> 
 发送时间: 2019年5月28日(星期&#x4E8C;) 下午2:31 
 收&#x4EF6;人: "Bigkoo/Android-PickerView"<Android-PickerView@noreply.github.com>; 
 抄送: "mingzaizai"<384627918@qq.com>;"Mention"<mention@noreply.github.com>; 
 主题: Re: [Bigkoo/Android-PickerView] 使用wheelView布局，滚动界面最顶端或者最低端出现了一个空白的选项，onItemSelected回调值-1 (#527) 
 
 
 
 我也遇到这个问题了，但是我不想更新版本，需要修改那些代码 ？ 
   
 &mdash; 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
&mdash;
